Opportunity to spawn dust effect with rotation of tank mesh
PushkinStudio/PsRealVehicle pull request #57
Opened 2017-12-11 14:45 UTC by dantonov

2017-12-11 14:57 UTC, ufna requested changes

2017-12-11 14:57 UTC, ufna commented on Source/PsRealVehiclePlugin/Classes/PrvVehicleMovementComponent.h
> +	UPROPERTY(EditDefaultsOnly, Category = Effects)
Добавь коммент-описание переменной

2017-12-12 08:47 UTC, ufna approved these changes

2017-12-12 09:14 UTC, Antonrr approved these changes

2017-12-12 09:14 UTC, merged