AWM-17410 Optimize movement component replicated data
PushkinStudio/PsRealVehicle pull request #61
Opened 2018-08-22 10:22 UTC by IlinAleksey

2018-08-22 13:01 UTC, Antonrr commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
Точно ли TrackEffectiveAngularSpeed влезет в int8?

Ещё как вариант предлагаю рассмотреть прореживание репликации, т.е. делать её не на каждый вызов, а при накоплении определённого deltatime (сделать конфигурируемым).

2018-08-22 13:37 UTC, IlinAleksey commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
Пока гонял не видел чтобы превышало 50 и -20

2018-08-22 14:21 UTC, Antonrr commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
50 — это уже половина до допустимого предела. Думаю, здесь лучше тоже передавать с уменьшенной точностью значение, чтобы защититься от overflow.

2018-08-22 14:22 UTC, ufna commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
@IlinAleksey , проконсультируйся с Игорем, как он скажет. Вообще по ощущениям uint8 хватит, просто клэпмить.

2018-08-22 14:22 UTC, ufna approved these changes

2018-08-22 14:25 UTC, ufna commented on Source/PsRealVehiclePlugin/Classes/PrvVehicleMovementComponent.h
> +	int8 RepLeftTrackEffectiveAngularSpeed;
Вообще, я бы запихнул это в структурку все три данных, и в одном онрепе это обрабатывал. Нет смысла делать три онрепа, которые по сути конвертят значения, которые постоянно меняются. Мол, FCosmeticRepData , что-то такое

2018-08-22 14:25 UTC, ufna requested changes
см. коммент, думаю это стоит сделать :)

2018-08-22 15:27 UTC, IlinAleksey commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
@Antonrr так ведь идёт клэмп [-127, 127]. overflow не будет, можем потерять значения больше 127 и меньше -127
@ufna спросил, на практике не замечал что доходило до 100. Если и будет доходить и переходить, то не страшно что мы обрежем до 127.

2018-08-22 15:34 UTC, ufna commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +	RepLeftTrackEffectiveAngularSpeed = static_cast<int8>(FMath::Clamp(FMath::RoundHalfFromZero(LeftTrackEffectiveAngularSpeed), -127.f, 127.f));
@IlinAleksey , тогда гуд

2018-08-23 09:29 UTC, IlinAleksey commented
Занёс в одну структуру

2018-08-23 14:54 UTC, ufna commented on Source/PsRealVehiclePlugin/Private/PrvVehicleMovementComponent.cpp
> +void UPrvVehicleMovementComponent::PrepareRepCosmeticData()
давай обзовём UpdateReplicatedCosmeticData() и можно мержить

2018-08-27 07:09 UTC, ufna commented
Просьба внимательнее к мелочам оформления.

2018-08-27 07:09 UTC, ufna approved these changes

2018-08-27 07:09 UTC, merged